"""
yara_gen.py
Automatically generates YARA rules based on analyzed malware reports in the database.
"""
import argparse
import os
from database import DatabaseManager

def generate_yara_rule(file_hash: str, output_dir: str = "."):
    db = DatabaseManager()
    
    if not db.sample_exists(file_hash):
        print(f"[-] Error: Hash {file_hash} not found in the database. Please analyze it first.")
        return

    # Fetch the typed report from our SQLite DB
    report = db.get_report(file_hash)
    
    # Clean the hash so it's a valid YARA rule name
    rule_name = f"Auto_Generated_{file_hash[:12]}"
    
    strings_section = []
    condition_section = ["uint16(0) == 0x5a4d"] # MZ header (Windows PE file)
    
    counter = 0
    
    # 1. Add Network IOCs (URLs)
    if report.iocs.urls:
        for url in report.iocs.urls:
            strings_section.append(f'        $url_{counter} = "{url}" ascii wide')
            counter += 1
        condition_section.append("any of ($url_*)")

    # 2. Add Network IOCs (IPs)
    if report.iocs.ips:
        for ip in report.iocs.ips:
            strings_section.append(f'        $ip_{counter} = "{ip}" ascii wide')
            counter += 1
        condition_section.append("any of ($ip_*)")

    # 3. Add Suspicious APIs (Limit to top 8 so the rule isn't overly generic)
    if report.suspicious_imports:
        for imp in report.suspicious_imports[:8]:
            strings_section.append(f'        $api_{counter} = "{imp.api}" ascii wide')
            counter += 1
        condition_section.append("any of ($api_*)")

    # Assemble the final YARA rule string
    yara_content = f"""rule {rule_name} {{
    meta:
        description = "Auto-generated by BinaryTrace"
        author = "Triage Engine"
        sha256 = "{file_hash}"
        risk_score = {report.risk_assessment.score}
        
    strings:
"""
    if strings_section:
        yara_content += "\n".join(strings_section)
    else:
        yara_content += '        $dummy = "THIS_RULE_HAS_NO_STRINGS" ascii'
        condition_section = ["$dummy"]

    yara_content += "\n\n    condition:\n        "
    
    # Construct the boolean logic (Must be a PE file AND contain some of our IOCs)
    if len(condition_section) > 1:
        yara_content += condition_section[0] + " and (" + " or ".join(condition_section[1:]) + ")"
    else:
        yara_content += condition_section[0]
        
    yara_content += "\n}\n"

    # Save it
    out_path = os.path.join(output_dir, f"{rule_name}.yar")
    with open(out_path, "w") as f:
        f.write(yara_content)
    
    print(f"[+] Successfully generated YARA rule!")
    print(f"[+] Saved to: {out_path}")

def main():
    parser = argparse.ArgumentParser(description="Automated YARA Rule Generator")
    parser.add_argument("hash", help="The SHA256 hash of the analyzed sample in your database")
    parser.add_argument("-o", "--outdir", help="Directory to save the .yar file", default="yara_rules")
    
    args = parser.parse_args()

    # Ensure output directory exists (drop it right into our existing yara_rules folder!)
    if not os.path.exists(args.outdir):
        os.makedirs(args.outdir)

    generate_yara_rule(args.hash, args.outdir)

if __name__ == "__main__":
    main()