rule Auto_Generated_1ccf6eab61da {
    meta:
        description = "Auto-generated by Enterprise Malware Analyzer"
        author = "Triage Engine"
        sha256 = "1ccf6eab61dabb654504fab6d70876d7bcbeba2140e27e3e3279ed0eabdb988a"
        risk_score = 50
        
    strings:
        $url_0 = "http://malicious-test.com" ascii wide
        $ip_1 = "192.168.100.50" ascii wide

    condition:
        uint16(0) == 0x5a4d and (any of ($url_*) or any of ($ip_*))
}
